### ISSUE TITLE
Running average for smooth PVOutput graphs is broken

### ISSUE THREAD

**Issue by kingfisher02** [markruys/gw2pvo#26] opened 2019-07-22 07:01 UTC
The running average for smooth PVOutput graphs is broken since the update from version 1.2.1 to 1.2.2. The resolution for produced energy is back to 0.1 kWh, so on a cloudy day it will report the same value multiple times and then increment with 0.1.

Before the update this worked correctly, but version 1.2.1 didn’t reset the produced energy back to 0 after midnight…

I am running gw2pvo version 1.2.2 on a RPi3. Both the script and PVOutput are set to a 5-minute interval.

**Example:**
https://www.pvoutput.org/intraday.jsp?id=77613&sid=68817

**Comment by markruys** [comment] 2020-06-29 20:12
This seems to be a duplicate of #20, so I close this issue.

**Closed by markruys** 2020-06-29 20:12 UTC
