### ISSUE TITLE
change to API URL?

### ISSUE THREAD

**Issue by JWDebler** [markruys/gw2pvo#21] opened 2019-07-08 10:42 UTC
I have been getting this error since earlier today:

`Jul 08 18:37:20 odroid gw2pvo[7181]: WARNING  HTTPSConnectionPool(host='globalapi.sems.com.cn', port=443): Max retries exceeded with url: /api/v1/PowerStation/GetMonitorDetailByPowerstationId (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb5c95a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Jul 08 18:37:47 odroid gw2pvo[7181]: ERROR    Failed to call GoodWe API
Jul 08 18:37:47 odroid gw2pvo[7181]: ERROR    'inverter'`

It looks like `globalapi.sems.com.cn` is not reachable anymore. Has goodwe maybe changed or removed that URL? I can see all my stats just fine on semsportal.

**Comment by walterwhite81** [comment] 2019-07-08 11:31
Same-ish- here: Jul  8 13:29:04 host gw2pvo[12799]: WARNING  HTTPSConnectionPool(host='globalapi.sems.com.cn', port=443): Max retries exceeded with url: /api/v1/PowerStation/GetMonitorDetailByPowerstationId (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fe99c58d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by RubenR** [comment] 2019-07-08 12:24
Same here:
INFO     Starting new HTTPS connection (1): globalapi.sems.com.cn
WARNING  ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by Uma1r** [comment] 2019-07-08 13:16
Yeah, DNS is not resolving.

**Comment by JaapBraam** [comment] 2019-07-08 13:22
New server name is https://euapi.sems.com.cn/api/

**Comment by walterwhite81** [comment] 2019-07-08 13:56
verified, globalapi.sems.com.cn working fine again.

euapi doesn't resolve for me.

**Closed** 2019-07-09 01:17 UTC
